sdss/lvmdrp

python/lvmdrp/functions/run_drp.py

This branch adds the `create_pixelmask` task to the main `run_drp` script. Some general changes are:
1. Reordering where master paths are defined
2. Added `mpixmask` master path
3. Producing pixel masks only after reducing bias, darks and pixelflats and no pixelmask was found
4. Adding `in_mask=mpixmask` to `preproc_raw_frame` task
This feature will help significantly improve flat and arc reductions.

Adding pixel mask task to main drp script

---

python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_drp.py

This PR adds a new function and pipeline step for combining the spectographs into a single file.  This combines the camera-combined ancillrary `lvm-object-sp[x]-[expnum].fits` files (3 files), for a given exposure, into the output `lvm-CFrame-[expnum].fits` file which will be input into the sky subtraction module.    The data are stacked as [sp1, sp2, sp3] which makes the data ordered "bottom-to-top", i.e. the 0-index array element is the start of sp1 fibers. 
The extensions of the file are:
- PRIMARY - primary header
- FLUX - the flux data (formerly data in extension 0)
- ERROR - the error data (until we switch it to IVAR) 
- MASK - the pixel mask (formerly BADPIX)
- WAVE - the 1d wavelength array
- FWHM - the measured FWHM (formerly INSTFWHM)
- SLITMAP - the full fibermap

Adds method for combining spectrographs into single new

---

python/lvmdrp/core/cube.py
python/lvmdrp/core/fiberrows.py
python/lvmdrp/core/image.py
python/lvmdrp/core/rss.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_drp.py
python/lvmdrp/functions/skyMethod.py

Fixing remaining double precision operations and I/O methods. Main changes are:
- Fixing `loadFitsData` methods to convert data to `float32`
- Fixing outputs from interpolation routines to be `float32`
- Fixing output from `all_pix2world` method to be `float32`
- Making sure all `writeFitsData` write `float32`

Fixing double precision in reduction operations and products

---

python/lvmdrp/core/rss.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_drp.py
python/lvmdrp/functions/run_quickdrp.py

Refactoring camera frames combination. Main changes are:
- Refactoring `glueRSS`, now `stack_rss` to stack RSS objects along given axis
- Adding missing `_sky_error` stacking
- Swapping channel first, spec second for spec first, channel second
- Deprecating ancillary `lvm-object-sp{123}-[expnum].fits` file in favor of `lvm-object-{brz}-[expnum].fits`

New frame combination scheme

---

python/lvmdrp/functions/run_drp.py
python/lvmdrp/functions/run_quickdrp.py
python/lvmdrp/functions/skyMethod.py

This PR enables the reduction of calibration frames like twilights and lamp exposures with the `quick-reduction` script. The outputs still be the same as with the science reductions.

Quick (science) reduction for calibration frames

---

python/lvmdrp/core/image.py
python/lvmdrp/core/plot.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/run_calseq.py
python/lvmdrp/functions/run_twilights.py
tests/conftest.py
tests/core/test_image.py
tests/functions/test_imageMethod.py
tests/utils/test_metadata.py

Implementing fix for pixel shifts detected in dome/twilight flats. Main changes are:
- Implementing detection of pixel shifts and corrections
- Implementing function to plot a image around pixel shifts
- Added as new pipeline step with the condition `imagetyp=='flat'`

Fix pixel shifts in dome/twilight flat images

---

python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_quickdrp.py

This PR fixes an issue where the DRP crashes when an exposure doesn't have all spectrograph or channels.  The original errors were seen in https://data.sdss5.org/sas/sdsswork/lvm/spectro/redux/master/drp_errors.txt. For example, 
```
ERROR on tileid, mjd, exposure: 1028742, 60216, 5755
Traceback (most recent call last):
File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/master/python/lvmdrp/functions/run_drp.py", line 1523, in run_drp
quick_science_reduction(expnum, use_fiducial_master=True)
File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdrp/master/python/lvmdrp/functions/run_quickdrp.py", line 279, in quick_science_reduction
flux_tasks.apply_fluxcal(in_rss=sci_path, out_rss=sci_path)
File "/uufs/chpc.utah.edu/common/home/sdss50/software/git/sdss/lvmdr …
```

Fixes crash when exposures missing spectrographs/channels.  

---

bin/drp
python/lvmdrp/utils/cluster.py

This PR adds a new function, `run_cluster`, and new CLI `drp cluster` to submit a slurm job to the Utah cluster.  it parallelizes the DRP run around MJDs, with the command `drp run -m MJD`.  It accepts options for submitting only a list of MJDs or an MJD range.  If not specified, will default to all MJDs in the LVM_DATA_S directory.  
This has been tested at Utah without submitting.  It still needs to be tested on the cluster to check things run properly.

Adds new cli for submitting utah cluster run

---

README.md
bin/drp

This PR adds a new cli, `drp get-calibs --help` to use `sdss-access` to download the master calibration frames from the Utah SAS.   Example usage to download all calib frames from 60255: `drp get-calibs -m 60255`.  This uses `sdss-access` to download the files, which puts them in the `$LVM_SANBOX/calib` relative to your `SAS_BASE_DIR`, e.g. `$SAS_BASE_DIR/sdsswork/lvm/sandbox/calib/`.  This mirrors the Utah SAS.  
```
Usage: drp get-calibs [OPTIONS]
Download the master calibration frames
Downloads the master calibration frames from the Utah SAS in
LVM_SANDBOX/calib.  This command only downloads files when they do not yet
exist on your local system.  To re-download existing files, first delete
your local files.
The syntax for the calibration files are …
```

Adds new cli to download master calibs

---

python/lvmdrp/core/fiberrows.py
python/lvmdrp/core/fit_profile.py
python/lvmdrp/core/image.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/run_calseq.py

Fixes the tracing algorithm for instabilities when applying constraints in fiber positions, amplitudes and widths. Now the fitting implements built-in constraints using the `least_sqrt` `bounds` parameter.
Also fixes bug in error propagation when interpolating masked pixels during tracing and overall improved handling of guess centroids.

Fix tracing algorithm

---

CHANGELOG.rst
python/lvmdrp/utils/metadata.py
setup.cfg

This PR closes #94 with an issue when the drpall summary rows were being written by multiple processes at the same time.  This PR uses the `lockfile` package to set up a lock on the drpall hdf5 file, during write, with a retry-timeout of 5 seconds.
This should now allow for safe updates/appends of the drpall file during cluster runs.  At the end of the cluster run, we can manually run the `convert_h5_to_fits` to also produce a FITS file version of the summary file, which can be easier for astronomers to use.

Fixes issues with parallel drpall generation

---

README.md
bin/drp
python/lvmdrp/main.py
python/lvmdrp/utils/cluster.py

Implementing CLI options to reduce a list of exposures given a list of exposure numbers from a file. Main changes are:
- Adding `-F` option to accept a file containing comma-separated or a column of exposure numbers.
- Updated README to reflect changes in the CLI and previous DRP updates.

Adding CLI to read exposures from file

---

python/lvmdrp/functions/skyMethod.py

This PR fixes a bug when writing out the skytable ancillary file.   Some science exposures were taken during twilight or early in the night, before the MJD nightly switch.   I examined 4053 lvmCFrame files in `master`, and 137 have `MJD` != `SMJD` in the headers.   The culprit MJDs were sporadic from 60177 up to 60500 (the last MJD I checked), with no pattern, so I don't think it's a larger bug in the code.   For a few cases, I also checked that the `MJD` and `SMJD` values in the `lvmCFrame` files match the values in their respective raw frame `sdR` files.  
The output reduction paths and metadata are correct, but if we're pulling info from the headers, we need to use the `SMJD` header keyword for the correct value.

fixes skytable mjd bug

---

.github/workflows/test.yaml
python/lvmdrp/core/rss.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_calseq.py
python/lvmdrp/functions/run_twilights.py
tests/functions/test_runtwilights.py

This PR implements a significant improvement in flat fielding. Main changes are:
- Smoothing is carried out after normalizing fibers and not over the raw twilights
- Implemented Niv's optimization of convolution kernel in `convolution_matrix` and vectorization
- Added QA plot to show flat fielded fiber profile
- Other bug fixes and improvements
Example of new flat field in b
versus old one
The low-frequency features in the old flat field have been removed in this new implementation (fixes #88)

Improving fiber flats

---

.gitignore
python/lvmdrp/utils/hdrfix.py
tests/data/lvmHdrFix-60255.yaml
tests/utils/test_hdrfix.py

This PR closes #123.  It improves the runtime of the `apply_hdrfix` function.    Adds some missing tests as well.
I profiled the `extract_metadata` function at Utah using MJD 60255, which has 1105 raw frame to process. Without the `apply_hdrfix`, `extract_metadata` takes 217 seconds to run, with the bulk of the time spent in `fits.getheader` (215 seconds).   With the original method, it took ~31000 seconds to run, with the bulk of the time spent in the `pathlib.Path.rglob` of `apply_hdrfix`.  This PR removes the pathlib rglob search and replaces it with an fnmatch check.  This reduces the time significantly.  With the  new `apply_hdrfix`, `extract_method` took 229 seconds to run, with the bulk time still spent in `fits.getheader`, 214 seconds with 13 seconds spent in `apply_hdrfix`.

improves runtime of apply_hdrfix

---

python/lvmdrp/core/image.py
python/lvmdrp/core/spectrum1d.py

This PR implements direct construction of the sparse projection matrix used in fiber extraction. Previously, we'd construct a dense matrix in numpy vectorized code and only convert to a sparse matrix before inverting. Now we directly construct the sparse matrix in unvectorized code. This leads to a speedup by a factor of 2 and much reduced memory usage.

Faster extraction

---

python/lvmdrp/main.py
python/lvmdrp/utils/timer.py

Add a Timer class in utils and use it to report profiling information from the main routine to follow execution times at utah.

Add profiling to most reduction steps

---

python/lvmdrp/core/cube.py
python/lvmdrp/core/fiberrows.py
python/lvmdrp/core/fluxcal.py
python/lvmdrp/core/image.py
python/lvmdrp/core/rss.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/cubeMethod.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/plotMethod.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_calseq.py
python/lvmdrp/functions/run_twilights.py
python/lvmdrp/functions/specialMethod.py

Consistently use bottleneck.nan{median,mean,...} instead of numpy equivalents.

Consistently use bottleneck

---

python/lvmdrp/core/fiberrows.py
python/lvmdrp/core/image.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/run_calseq.py

Tracing of fibers can failed for different reasons but the pipeline should be able to fill in gaps using neighboring good fibers through interpolation. Failed edge fibers should be filled in by extrapolation. This PR fixes several issues preventing the behavior described above.
Main changes are:
- Better logging of failed traces
- Consistent values for invalid/non-sampled pixels (all NaNs)
- Fixes propagation of mask on failed fibers
This PR fixes #168.

Fixes failed tracing of edge fibers

---

bin/drp
python/lvmdrp/main.py
python/lvmdrp/utils/cluster.py
python/lvmdrp/utils/metadata.py

This PR replaces the creation/updating of the drpall summary file in cluster runs to prevent #166.
Main changes are:
- Implemented optional version parameter for metadata routines
- Implemented optional skipping of drpall file creation
- By default skipping drpall creation in cluster runs
- Implemented CLI to create drpall files for the given versions
- Better handling of invalid values to avoid casting float into strings and viceversa
This changes imply that we now have to run the creation of the drpall file after the cluster run are done.
This PR fixes #166.

Fixes race condition errors on writing DRPAll file

---

python/lvmdrp/core/fiberrows.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/main.py

This PR fixes issues with calibrations in epoch 60177. Main changes are:
- Implementing of interpolation of missing guess centroids
- Implementing determination of exposed standard fiber in arc exposure
With these changes we are always ensuring a guess centroid for the arc line measurements and that we skip standard fibers that were not exposed. Both will have an impact on calibrations for other epochs as well.

Fixing wavelength and LSF fitting for 60177

---

python/lvmdrp/core/image.py
python/lvmdrp/core/plot.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/rssMethod.py

in v1.1.0 some tile reductions failed to measure correctly both thermal shifts in Y and X directions. This PR implements a features in `_fix_fiber_thermal_shifts` and `shift_wave_skylines` to make those measurements more robust against large thermal shifts.

Refined thermal shift measurements

---

python/lvmdrp/core/image.py
python/lvmdrp/core/plot.py
python/lvmdrp/core/rss.py
python/lvmdrp/core/sky.py
python/lvmdrp/etc/dataproducts/calibration/lvmThroughput_bp.yaml
python/lvmdrp/etc/dataproducts/lvmCFrame_bp.yaml
python/lvmdrp/etc/dataproducts/lvmFFrame_bp.yaml
python/lvmdrp/etc/dataproducts/lvmFrame_bp.yaml
python/lvmdrp/etc/dataproducts/lvmRss_bp.yaml
python/lvmdrp/etc/dataproducts/lvmSFrame_bp.yaml
python/lvmdrp/functions/fluxCalMethod.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/skyMethod.py
python/lvmdrp/main.py
python/lvmdrp/utils/metadata.py

This PR fixes several header issues in science reduction products, namely:
- Missing units in several extensions (fixes #138)
- Missing header keyword comments in metadata produced by the DRP (fixes #77)
- Removes redundant information
- Adds per-camera information to combined frames
- Fixes comment truncation
- Normalizes style of comments
- Several bug fixes around headers

Fixing missing/redundant header information

---

python/lvmdrp/core/constants.py
python/lvmdrp/core/sky.py
python/lvmdrp/external/shadow_height_lib.py

Implementing single source for "de421.bsp" ephemeris file across the pipeline. Main changes:
- Defined path to ephemeris as constant pointing to `lvmcore/etc`
- Setup loader to this single source for SH and sky parameter calculations
- Fixed potential issue with loader being defined within conditional and referenced later

Setting single source of ephemeris at lvmcore

---

bin/drp
python/lvmdrp/main.py

This PR implements a CLI (`drp cache-gaia-xp`) to cache Gaia XP spectra in advance given a set of MJDs. Optionally we can set the minimum number of acquired standard stars to skip the caching. By default no skipping is done.
This solution will prevent the race condition issue while downloading Gaia XP spectra for science field calibration in cluster or any parallel run.

adding CLI to pre-cache Gaia XP spectra

---

python/lvmdrp/core/image.py
python/lvmdrp/core/spectrum1d.py

In 1.1.1dev data a number of exposures (e.g., 5006, 5336) have failed fiber thermal shift measurements. Here are some examples:
https://data.sdss5.org/sas/sdsswork/lvm/spectro/redux/1.1.1dev/0011XX/11111/60208/ancillary/qa/lvm-xobject-b2-00005336_fiber_thermal_shifts.png
https://data.sdss5.org/sas/sdsswork/lvm/spectro/redux/1.1.1dev/0011XX/11111/60202/ancillary/qa/lvm-xobject-z2-00005006_fiber_thermal_shifts.png
These failure seems to originate in the first guess of the fiber thermal shift coming from `align_blocks` when a few fibers dominate one or more blocks.
This PR fixes this issue by removing as much as possible fiber features during `align_blocks` so that only fiber blocks are cross matched.

Fiber thermal shift refinement

---

python/lvmdrp/functions/fluxCalMethod.py

This PR implements a better selection of the flux calibration selection by comparing the average sensitivity.
Main changes are:
- Once the average sensitivity is calculated for standard and science, it selects the method with the best (<1e-12) sensitivity
- Adds the missing average and RMS sensitivity to the `FLUXCAL_SCI` table
- Preserves the standard sensitivities even if <8 standard stars
- Fixes NaN in standard sensitivity header keywords
- Selection of calibration method happens in one routine

Improved flux calibration method selection

---

python/lvmdrp/core/image.py
python/lvmdrp/core/plot.py
python/lvmdrp/core/resample.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/rssMethod.py

This PR fixes a couple error propagation issues and adds QA plots to keep track of error propagation in several data reduction stages.
Main changes are:
- Removes faulty error propagation in CR rejection
- Removes density conversion of inverse variance in flux conserving resampling
- Adds QA plots to check error propagation in detrending, extraction, wavelength rectification

Fixes error propagation

---

bin/drp
python/lvmdrp/core/constants.py
python/lvmdrp/core/fiberrows.py
python/lvmdrp/core/fit_profile.py
python/lvmdrp/core/plot.py
python/lvmdrp/core/rss.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_calseq.py
python/lvmdrp/functions/run_twilights.py
python/lvmdrp/main.py
python/lvmdrp/utils/paths.py

We discovered that exposures of ~ 10s can show large inconsistencies in count levels between spectrographs due to shutter timing effects. This PR aims at mitigating those effects by fitting the spectrograph-to-spectrograph flat field using sky lines in science exposures.
The main changes are:
- Implemented simultaneous IFU "linear" gradient and spec-to-spec factors fitting
- Implemented science frame spec-to-spec factors fitting
- Added/Updated CLI for current fiber flatfielding routines
- Implemented useful QA plots
- Improved/Fixed error propagation for FiberRows/RSS objects
- Bug fixes and other improvements all around
TODOs:
- Implement automatic rejection of faulty twilights from a given sequence
- Implement automatic selection of science frames for spec-to-spec factors fitting …

New fiber flat fielding

---

python/lvmdrp/core/fit_profile.py
python/lvmdrp/core/image.py
python/lvmdrp/core/plot.py
python/lvmdrp/core/rss.py
python/lvmdrp/core/spectrum1d.py
python/lvmdrp/core/tracemask.py
python/lvmdrp/etc/dataproducts/lvmCFrame_bp.yaml
python/lvmdrp/etc/dataproducts/lvmSFrame_bp.yaml
python/lvmdrp/functions/fluxCalMethod.py
python/lvmdrp/functions/imageMethod.py
python/lvmdrp/functions/rssMethod.py
python/lvmdrp/functions/run_calseq.py
python/lvmdrp/functions/skyMethod.py

Implements sensitivity curves propagations as extensions from lvmFFrames downstream to lvmSFrame. Main changes are:
- Implements spectrograph channel combine of sensitivity curves using the same weighing schema used for RSS
- Implements flux calibration swapping method to seamlessly change from standard to science field stars calibrations
- Implements propagation of sensitivity curve extensions from lvmFFrame to lvmSFrame products

Sensitivity curve propagation

---

python/lvmdrp/functions/fluxCalMethod.py

Gaia star ids were saved to the array before filtering out the standard stars with low fluxes. Because of this, the wrong Gaia stars were assigned to the given standards. It only occurred when we had a standard with a low flux; in other cases, it worked fine. Now it's fixed

Fixed the bug in the prepare_spec. 
